[package]
name = "sqlynx-platform"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

workspace = "../../"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1"
tonic = "^0.10.2"
prost = "^0.12.3"
once_cell = "1.19.0"
tokio = { version = "^1.35.1", features = ["rt", "rt-multi-thread", "sync", "macros"] }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6", "channel-api"]
